export default {
  // Base
  SET_IS_LOADING: 'SET_IS_LOADING',
  SET_APP_READY: 'SET_APP_READY',
  // Auth
  SET_IS_LOGGEDIN: 'SET_IS_LOGGEDIN',
  SET_INVITATION_CODE: 'SET_INVITATION_CODE',
  // User
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  // Challenge
  SHOW_START_CHALLENGE_MODAL: 'SHOW_START_CHALLENGE_MODAL',
  HIDE_START_CHALLENGE_MODAL: 'HIDE_START_CHALLENGE_MODAL',
  SET_DONE_GIFE_PLACE_MODAL_VISIBLE: 'SET_DONE_GIFE_PLACE_MODAL_VISIBLE',
};
