export default {
  // Base
  SET_IS_LOADING: 'SET_IS_LOADING',
  SET_APP_READY: 'SET_APP_READY',
  // Auth
  SET_IS_LOGGEDIN: 'SET_IS_LOGGEDIN',
  SET_INVITATION_CODE: 'SET_INVITATION_CODE',
  // User
  SET_AUTH_USER: 'SET_AUTH_USER',
  // Challenge
  SET_DO_CHALLENGE_MODAL_VISIBLE: 'SET_DO_CHALLENGE_MODAL_VISIBLE',
  SET_DONE_GIFE_PLACE_MODAL_VISIBLE: 'SET_DONE_GIFE_PLACE_MODAL_VISIBLE',
};