export default {
  // Base
  SET_IS_LOADING: 'SET_IS_LOADING',
  // Auth
  SET_IS_LOGGEDIN: 'SET_IS_LOGGEDIN',
  SET_INVITATION_CODE: 'SET_INVITATION_CODE',
  // Challenge
  SET_DO_CHALLENGE_MODAL_VISIBLE: 'SET_DO_CHALLENGE_MODAL_VISIBLE',
  SET_DONE_GIFE_PLACE_MODAL_VISIBLE: 'SET_DONE_GIFE_PLACE_MODAL_VISIBLE',
};